# Generated by Django 4.2.17 on 2025-01-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_field_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=80),
        ),
    ]
