# Generated by Django 4.2.17 on 2025-01-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='field_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
